# Generated by Django 4.2.16 on 2026-05-26 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('gelir', 'Gelir'), ('gider', 'Gider')], max_length=10, verbose_name='Tür')),
                ('payment_method', models.CharField(choices=[('nakit', 'Nakit'), ('havale', 'Havale')], max_length=10, verbose_name='Ödeme Yöntemi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar (₺)')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
