# Generated by Django 4.2.16 on 2026-03-30 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('kursiyer', 'Kursiyer'), ('ozel_ders', 'Özel Ders'), ('aqua_fitness', 'Aqua Fitness')], max_length=20, unique=True, verbose_name='Tip')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('session_count', models.PositiveIntegerField(verbose_name='Seans sayısı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Paket türü',
                'verbose_name_plural': 'Paket türleri',
                'ordering': ['session_count'],
            },
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(verbose_name='Toplam seans')),
                ('remaining_sessions', models.PositiveIntegerField(verbose_name='Kalan seans')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atanma tarihi')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Bitiş tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_packages', to=settings.AUTH_USER_MODEL, verbose_name='Atayan')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packages.packagetype', verbose_name='Paket türü')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL, verbose_name='Üye')),
            ],
            options={
                'verbose_name': 'Üye paketi',
                'verbose_name_plural': 'Üye paketleri',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
