# Generated by Django 4.2.16 on 2026-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ödeme tarihi'),
        ),
        migrations.AddField(
            model_name='userpackage',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Başlangıç saati'),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='slug',
            field=models.CharField(choices=[('kursiyer', 'Kursiyer'), ('ozel_ders', 'Özel Ders'), ('deneme_dersi', 'Deneme Dersi')], max_length=20, unique=True, verbose_name='Tip'),
        ),
    ]
