# Generated by Django 4.2.16 on 2026-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_add_start_time_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetype',
            name='slug',
            field=models.CharField(choices=[('kursiyer', 'Kursiyer (8 Seans)'), ('kursiyer_4', 'Kursiyer (4 Seans)'), ('ozel_ders', 'Özel Ders'), ('deneme_dersi', 'Deneme Dersi')], max_length=20, unique=True, verbose_name='Tip'),
        ),
    ]
