# Generated by Django 4.2.16 on 2026-05-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='swim_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 (başlangıç) — 10 (ileri seviye)', null=True, verbose_name='Yüzme seviyesi'),
        ),
    ]
