# Generated by Django 4.2.16 on 2026-05-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_instructor_alter_appointment_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attended',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Geldi'),
        ),
    ]
