# Generated by Django 4.2.16 on 2026-06-01 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_cascade_user_package_delete'),
        ('appointments', '0003_add_attended_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='packages.userpackage', verbose_name='Kullanılan paket'),
        ),
    ]
